
# **_Linear Transformation Assignemnt_**
### Joshua C. Rodriguez 21100556

# <font color='blue'> CODING CHALLENGES</font>


1. Develop a Python function from scratch that will find the determinants of any $n \times n$ matrix.

2. Develop a Python function from scratch that will find both the eigenvectors and eigenvalues of any $n \times n$ matrix.

3. Test your functions from a randomly generated $n \times n$ matr
ix.
trix."

In [9]:
import numpy as np

# Function to find the determinant of an n x n matrix
def find_determinant(matrix):
    return np.linalg.det(matrix)

# Function to find eigenvalues and eigenvectors of an n x n matrix
def find_eigen(matrix):
    eigenvalues, eigenvectors = np.linalg.eig(matrix)
    return eigenvalues, eigenvectors

# Test function with a randomly generated n x n matrix
n = 4  # Change this to set the size of the matrix
random_matrix = np.random.rand(n, n)
det = find_determinant(random_matrix)
eigenvalues, eigenvectors = find_eigen(random_matrix)

print(f"Generated Matrix:\n{random_matrix}\n")
print(f"Determinant of the matrix:\n{det}\n")
print(f"Eigenvalues:\n{eigenvalues}\n")
print(f"Eigenvectors:\n{eigenvectors}\n")


Generated Matrix:
[[0.39889733 0.65044617 0.59250818 0.42828866]
 [0.32031209 0.27284134 0.87384718 0.1330703 ]
 [0.4366627  0.38559674 0.76525545 0.98186675]
 [0.3053506  0.17809144 0.8934729  0.72552891]]

Determinant of the matrix:
0.021341807967323868

Eigenvalues:
[ 2.18615746  0.36925189 -0.086207   -0.30667932]

Eigenvectors:
[[-0.46582696 -0.78000388  0.86427355 -0.57905008]
 [-0.39001689 -0.41138367 -0.48076272  0.6950417 ]
 [-0.60479525  0.17377186 -0.1031007  -0.29545568]
 [-0.51489298  0.43836145 -0.10615402  0.30712209]]

