**Name:** Joshua C. Rodriguez
                                                        **ID:** 21100556

# <font color = blue> ASSIGNMENT 1</font>
- To complete the process of determining the solution, create a function or steps of function that will automate backward substitution.

In [18]:
import numpy as np

def row_swap(A, k, l):
    
    B = np.copy(A).astype('float64')
    B[[k, l], :] = B[[l, k], :]
    return B

def row_scale(A, k, scale):
   
    B = np.copy(A).astype('float64')
    B[k, :] *= scale
    return B

def row_add(A, k, l, scale):
   
    B = np.copy(A).astype('float64')
    B[l, :] += B[k, :] * scale
    return B


def backward_substitution(U,y):
    """
    Performs backward substitution.

    Args:
        U: A numpy array of shape (n, n). It should be the U from the 
            QR factorization.
        y: A numpy array of shape (n,). It should be the output vector from the
            QR factorization.

    Returns:
        A numpy array of shape (n,) that is the solution to the linear system.
    """
    n = U.shape[0]
    x = np.zeros(n)

    # Perform backward substitution
    for i in range(n-1, -1, -1):
        x[i] = (y[i] - np.dot(U[i, i+1:], x[i+1:])) / U[i, i]

    return x

A = np.array([[1, -1, 1, 3], [2, 1, 8, 18], [4, 2, -3, -2]])

A1 = row_add(A, 0, 1, -2)
print("A1")
print(A1, '\n')

A2 = row_add(A1, 0, 2, -4)
print("A2")
print(A2, '\n')

A3 = row_add(A2, 1, 2, -2)
print("A3")
print(A3, '\n')

A4 = row_scale(A3, 1, 1.0/3)
print("A4")
print(A4, '\n')

A5 = row_scale(A4, 2, 1.0/-19.)
print("A5")
print(A5, '\n')

# Use the backward substitution to find the solutions
solutions = backward_substitution(A5[:, :-1], A5[:, -1])
# Print the solutions
for i, sol in enumerate(solutions):
    print(f"a{i + 1} = {sol}")


A1
[[ 1. -1.  1.  3.]
 [ 0.  3.  6. 12.]
 [ 4.  2. -3. -2.]] 

A2
[[  1.  -1.   1.   3.]
 [  0.   3.   6.  12.]
 [  0.   6.  -7. -14.]] 

A3
[[  1.  -1.   1.   3.]
 [  0.   3.   6.  12.]
 [  0.   0. -19. -38.]] 

A4
[[  1.  -1.   1.   3.]
 [  0.   1.   2.   4.]
 [  0.   0. -19. -38.]] 

A5
[[ 1. -1.  1.  3.]
 [ 0.  1.  2.  4.]
 [-0. -0.  1.  2.]] 

a1 = 1.0
a2 = 0.0
a3 = 2.0


# <font color = blue> Assignment 2 </font>
---

### 1. Provide reasons why each of the following equations is, or is not, a linear equation.

- $\cos{\theta}x+4y+z = \sqrt{3}$ <br><br>This equation is non-linear due to the presence of the trigonometric term cos(x) and the non-homogeneous term 4y, both of which violate the conditions for linearity.
- $cos{x}4y+z = \sqrt{3}$ <br><br> Not a linear equation because The nonlinearity rises from the existence of the cosine function and the multiplication of y by 4.
- $x^{-1}+7y+z = \sin{(\frac{\pi}{2})}$ <br><br> Not a linear equation because the presence of $x^{-1}$ and the sine function goes against the conditions of linearity.
- $x^1+y^1+z^1=0$ <br><br> Considered a  linear equation because this equation is linear because the variables are raised to the first power, and the coefficients are all 1.


### 2.Find the solutions to the linear equations:


<br>
$2x_1+3x_2 =5$<br> <br>
$2x_1 = 5 - 3x_2$<br>
$x_1 = \frac{5}{2} - \frac{3}{2}x_2$ <br>
$x_2 = \frac{5}{3} - \frac{2}{3}x_1$ <br><br><br>

$4x_1 + 3x_2 + 2x_3 = 1$<br><br>
$x_1 = \frac{1}{4} - \frac{3}{4}x_2 - \frac{1}{2}x_3$<br>
$x_2 = \frac{1}{3} - \frac{4}{3}x_1 - \frac{2}{3}x_3$<br>
$x_3 = \frac{1}{2} - \frac{3}{2}x_2 - 2x_1$<br><br><br>

$3x - 6y = 0$<br><br>
$3x = 6y$<br>
$x = 2y$<br>
$\frac{1}{2}x = y$


   

### 3. Solve the following systems of linear equations


$ x - y = 0 $<br>$ 2x + y = 3$
 <br>

- $-2(x - y = 0)$
- $-2x + 2y = 0$

<br>

- $\frac{3y}{3} = \frac{3}{3}$
- $y = 1$

<br>

- $x - 1 = 0$
- $x = 1$

<br>

- $x = 1, \ y = 1$

In [17]:
#Check using pythonic solution
import numpy as np

A, b = np.array([[1, -1], [2, 1]]), np.array([0, 3])
solution = np.linalg.solve(A, b)

print("Solution:\n", "x =", solution[0], "\n", "y =", solution[1])

Solution:
 x = 1.0 
 y = 1.0


$x + 5y = -1$<br>$-x + y = -5$<br>$ 2x + 4y = 4$ <br><br>


$
\begin{pmatrix}
    1 & 5 &\bigm| & -1 \\
    -1 & 1 &\bigm| & -5 \\
    2 & 4 &\bigm| & 4 \\
\end{pmatrix}
\xrightarrow[\text{R}_{3} - 2\text{R}_{1}]{\text{R}_{2} + \text{R}_{1}}
\begin{pmatrix}
    1 & 5 &\bigm| & -1 \\
    0 & 6 &\bigm| & -6 \\
    0 & -6 &\bigm| & 6 \\
\end{pmatrix}
\xrightarrow[\text{R}_{3}(\frac{1}{6})]{\text{R}_{2}(\frac{1}{6})}
\begin{pmatrix}
    1 & 5 &\bigm| & -1 \\
    0 & 1 &\bigm| & -1 \\
    0 & -1 &\bigm| & 1 \\
\end{pmatrix}
\xrightarrow[\text{R}_{3} + \text{R}_{2}]{}
\begin{pmatrix}
    1 & 5 &\bigm| & -1 \\
    0 & 1 &\bigm| & -1 \\
    0 & 0 &\bigm| & 0 \\
\end{pmatrix}
% \xrightarrow[\text{R}_{1} - 5\text{R}_{2}]{}
% \begin{pmatrix}
%     1 & 0 &\bigm| & 4 \\
%     0 & 1 &\bigm| & -1 \\
%     0 & 0 &\bigm| & 0 \\
% \end{pmatrix}
$ 
<br><br> 
        - y = -1
<br>
        - x + 5(-1) = -1
        - x + -5 = -1
        - x = 5 + (-1)
        - x = 4
        - $x = 4, \ y = -1$

In [13]:
import numpy as np

coeff_matrix, constants = np.array([[1, 5], [-1, 1], [2, 4]]), np.array([-1, -5, 4])
solution = np.linalg.lstsq(coeff_matrix, constants, rcond=None)[0]

print("Solution:\n", "x =", solution[0], "\n", "y =", solution[1])


Solution:
 x = 4.000000000000001 
 y = -0.9999999999999998


- $2x_1 + 3x_2 - x_3 = -1 $ <br>$ x_1 + x_3 = 0$ <br> $ -x_1 + 2x_2 - 2x_3  = 0$ <br><br>
$$
\begin{pmatrix}
     2 &  3 & -1 &\bigm| & -1 \\
     1 &  0 &  1 &\bigm| &  0 \\
    -1 &  2 & -2 &\bigm| &  0 \\
\end{pmatrix}
$$


\begin{equation}
\begin{pmatrix}
    2 & 3 & -1 & \bigm| & -1 \\
    1 & 0 & 1 & \bigm| & 0 \\
    -1 & 2 & -2 & \bigm| & 0 \\
\end{pmatrix}
\end{equation}

\begin{equation}
\begin{pmatrix}
0 & 3 & -3 & \bigm| & -1 \\
1 & 0 & 1 & \bigm| & 0 \\
-1 & 2 & -2 & \bigm| & 0 \\
\end{pmatrix}
\end{equation}

\begin{equation}
\begin{pmatrix}
0 & 3 & -3 & \bigm| & -1 \\
1 & 0 & 1 & \bigm| & 0 \\
0 & 2 & -1 & \bigm| & 0 \\
\end{pmatrix}
\end{equation}

\begin{equation}
\begin{pmatrix}
0 & 1 & -2 & \bigm| & -1 \\
1 & 0 & 1 & \bigm| & 0 \\
0 & 2 & -1 & \bigm| & 0 \\
\end{pmatrix}
\end{equation}

\begin{equation}
\begin{pmatrix}
0 & 1 & -2 & \bigm| & -1 \\
1 & 0 & 1 & \bigm| & 0 \\
0 & 0 & 3 & \bigm| & 2 \\
\end{pmatrix}
\end{equation}

\begin{equation}
\begin{pmatrix}
0 & 1 & -2 & \bigm| & -1 \\
1 & 0 & 1 & \bigm| & 0 \\
0 & 0 & 1 & \bigm| & \frac{2}{3} \\
\end{pmatrix}
\end{equation}

\begin{equation}
\begin{pmatrix}
1 & 0 & 1 & \bigm| & 0 \\
0 & 1 & -2 & \bigm| & -1 \\
0 & 0 & 1 & \bigm| & \frac{2}{3} \\
\end{pmatrix}
\end{equation}



$x_1 + x_3 = 0$<br>
$x_2 - 2x_3 = -1$<br>
$x_3 = \frac{2}{3}$<br><br>

$x_1 + \frac{2}{3} = 0$<br>
$x_1 = -\frac{2}{3}$<br><br>

$x_2 - 2(\frac{2}{3}) = -1$<br>
$x_2 - \frac{4}{3} = -1$<br>
$x_2 = -1 + \frac{4}{3}$ <br>
$x_2 = \frac{1}{3}$<br>


### 4. Provide reasons why the given matrices are either a row echelon, a reduced row echelon, or niether both.


a. <br>
\begin{pmatrix}
   1 & 0 & 1 \\
   0 & 0 & 3 \\
   0 & 1 & 0 \\
\end{pmatrix}<br><br>
**Row Echelon Form**<br>
This matrix meets the criteria for row echelon form. However, it does not satisfy the conditions for reduced row echelon form as the leading non-zero entry in the second row is not the only non-zero entry in its column.

b. <br>
\begin{pmatrix}
   7 & 0 & 1 & 0 \\
   0 & 1 & -1 & 4 \\
   0 & 0 & 0 & 0 \\
\end{pmatrix}<br><br>
**Row Echelon Form**<br>
The first non-zero entry in each row is to the right of the first non-zero element in the row above it.
All zero rows are placed at the bottom.
However, it does not satisfy the conditions for reduced row echelon form because

The leading non-zero entries (7 and 1) are not the only non-zero entries in their respective columns.


c. <br>
\begin{pmatrix}
   0 & 1 & 3 & 0 \\
   0 & 0 & 0 & 1 \\
\end{pmatrix}<br><br>
**Row Echelon Form**<br>
The first non-zero entry in each row is to the right of the first non-zero element in the row above it.
All zero rows are placed at the bottom.
However, it does not satisfy the conditions for reduced row echelon form because:

The leading non-zero entries (1 in the first row and 1 in the second row) are not the only non-zero entries in their respective columns.

d. <br>
\begin{pmatrix}
   0 & 0 & 0 \\
   0 & 0 & 0 \\
   0 & 0 & 0 \\
\end{pmatrix}<br><br>
**Neither in row echelon form nor in reduced row echelon form** <br>
This matrix is neither in row echelon form nor in reduced row echelon form due to the absence of non-zero entries that would enable assessment against the criteria for these forms.

e. <br>
\begin{pmatrix}
   1 & 0 & 3 & -4 & 0 \\
   0 & 0 & 0 & 0 & 0 \\
   0 & 1 & 5 & 0 & 1 \\
\end{pmatrix}<br><br>

**Row Echelon Form**<br>
 The given matrix is in row echelon form but not in reduced row echelon form.
 The first non-zero entry in each row is to the right of the first non-zero element in the row above it.
All zero rows are placed at the bottom.
However, it does not satisfy the conditions for reduced row echelon form becau 

The leading non-zero entries (1 in the first row and 1 in the third row) are not the only non-zero entries in their respective columns.
The leading entry in the third row (1) is not the only non-zero entry in its column.


f. <br>
\begin{pmatrix}
   0 & 0 & 1 \\
   0 & 1 & 0 \\|
   1 & 0 & 0 \\
\end{pmatrix}<br><br>

**Reduced Row Echelon** <br>
The first non-zero entry in each row is to the right of the first non-zero element in the row above it.
Additionally, this matrix satisfies the conditions for reduced row echelon for. 

The leading non-zero entries (1 in each row) are the only non-zero entries in their respective columns.

g. <br>
\begin{pmatrix}
   1 & 2 & 3 \\
   1 & 0 & 0 \\
   0 & 1 & 1 \\
   0 & 0 & 1 \\
\end{pmatrix}<br><br>

**Not in Row Echelon Form and as well as Reduced Row Echelon Form**<br>
1.) It does not satisfy the conditions 

h. <br>
\begin{pmatrix}
   2 & 1 & 3 & 5 \\
   0 & 0 & 1 & -1 \\
   0 & 0 & 0 & 3 \\
   0 & 0 & 0 & 0 \\
\end{pmatrix}

**Row Echelon Form**<br>

The given matrix is in row echelon form but not in reduced row echelon form.This matrix satisfies the criteria for row echelon form:

The first non-zero entry in each row is to the right of the first non-zero element in the row above it.
All zero rows are placed at the bottom.
However, it does not satisfy the conditions for reduced row echelon form because the leading non-zero entries (2, 1, and 3) are not the only non-zero entries in their respective columns.

### 5. Solve the equations

$$
\begin{align}
    x_1 + 2x_2 - 3x_3 = 9 \\
    2x_1 - x_2 - x_3 = 0 \\
    4x_1 - x_2 + x_3 = 4 \\
\end{align}
$$

In [27]:
import numpy as np

A = np.array([[1, 2, -3],
              [2, -1, -1],
              [4, -1, 1]])

b = np.array([9, 0, 4])

solution = np.linalg.solve(A, b)

for i, x in enumerate(solution, start=1):
    print(f"x{i} = {x}")


x1 = 1.9
x2 = 3.6999999999999997
x3 = 0.10000000000000003


$$
\begin{align}
    x + 2y= -1 \\
    2x + y + z = 1 \\
    -x + y - z = -1
\end{align}
$$


In [28]:
import numpy as np

M = np.array([[1, 2, 0],
              [2, 1, 1],
              [-1, 1, -1]])

if np.linalg.det(M) == 0:
    print("No solution")
else:
    print("Determinant of M:", np.linalg.det(M))


No solution


$$
\begin{align}
    w + x + 2y + z = 1 \\
    w - x - y + z = 0 \\
    x + y = 1 \\
    w + x + z = 2
\end{align}
$$

In [29]:
import numpy as np

M = np.array([[1, 1, 2, 1],
              [1, -1, -1, 1],
              [0, 1, 1, 0],
              [1, 1, 0, 1]])

if np.linalg.det(M) == 0:
    print("Solution exists")
else:
    print("Determinant of M:", np.linalg.det(M))


Solution exists
